apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    app: my-nginx
spec:
  containers:
    - name: my-nginx
      image: 192.168.1.10:8443/my_nginx
      ports:
      - containerPort: 80
      volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: nfs-vol
  volumes:
    - name: nfs-vol
      persistentVolumeClaim:
        claimName: jenkins-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: np-svc
spec:
  selector:
    app: my-nginx
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30000
  type: NodePort
