apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
spec:
  containers:
    - name: my-nginx
      image: --image=192.168.1.10:8443/indexfile_for_jenkins_test
      ports:
      - containerPort: 8080
      volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: nfs-vol
  volumes:
    - name: nfs-vol
      persistentVolumeClaim:
        claimName: jenkins
---
apiVersion: v1
kind: Service
metadata:
  name: np-svc
spec:
  selector:
    app: my-nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000
  type: NodePort
